language: java
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
    - os: windows
      language: shell
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export JAVA_HOME=${JAVA_HOME:-/c/jdk}
      && export PATH=${JAVA_HOME}/bin:${PATH}
      && choco install jdk8 -params 'installdir=c:\\jdk' -y;
    fi
install:
  - ./gradlew :tools:api-classes-generator:build
  - ./gradlew :wrapper:godot-library:build
  - ./gradlew :wrapper:godot-library-extension:build
  - ./gradlew :tools:godot-gradle-plugin:build
deploy:
  provider: mvn
  api_key:
    secure: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true